#These are my settings I use for llama.cpp (vulkan) using my Thinkpad T14 gen 2, which is a potato
#system specs are Memory: 15gb /Processor: Intel Core i5-1145G7 /OS: Cachy OS

#My favorite models are Mellum 2 12B (around 11 tok/s), Gemma 4 E4B (around 7 tok/s), and Granite 4.0 tiny (around 7 tok/s)

#This file is designed to be ran with the command: llama-server --models-preset /path/to/models.ini

#For more information about Llama.cpp: https://github.com/ggml-org/llama.cpp
#For more information about Llama-server: https://github.com/ggml-org/llama.cpp/tree/master/tools/server 

#If you have any suggestions for improvements please feel free to post or email me at ava@cathousedev.com

[Gemma 4 E2B]
#https://huggingface.co/unsloth/gemma-4-E2B-it-qat-mobile-GGUF
#8.0 tok/s @ 1000 tok
model = /home/ava/LLMs/gemma_4_E2B/gemma-4-E2B-it-qat-UD-Q2_K_XL.gguf
model-draft = /home/ava/LLMs/gemma_4_E2B/gemma-4-E2B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-n-min = 2
ctx-size = 20000
reasoning-budget = 300
reasoning-budget-message = "I need to wrap this up and answer right now"
temp = 1.0
top-p = 0.95
min-p = 0.05
top-k = 64

[Gemma 4 E4B]
#https://huggingface.co/unsloth/gemma-4-E4B-it-qat-mobile-GGUF
#6.8 tok/s @ 1000 tok
model = /home/ava/LLMs/gemma_4_E4B/gemma-4-E4B-it-qat-UD-Q2_K_XL.gguf
model-draft = /home/ava/LLMs/gemma_4_E4B/gemma-4-E4B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-n-min = 2
ctx-size = 20000
reasoning-budget = 300
reasoning-budget-message = "I need to wrap this up and answer right now"
temp = 1.0
top-p = 0.95
min-p = 0.05
top-k = 64

[Granite 4.0 Tiny (7B-A1B)]
#https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF
#11.7 tok/s @ 1000 tok
model = /home/ava/LLMs/granite-4.0-h-tiny-Q4_K_M.gguf
ctx-size = 20000
reasoning = on
reasoning-budget-message = "I need to wrap this up and give an answer now"
temp = 1.0
top-p = 0.95
min-p = 0.05
top-k = 65

[Mellum 2 12B-A2B]
#https://huggingface.co/JetBrains/Mellum2-12B-A2.5B-Thinking
#7.7 tok/s @ 1000 tok
model = /home/ava/LLMs/Mellum2-12B-A2.5B-Instruct-Q4_K_M.gguf
ctx-size = 10000
reasoning = off
temp = 1.0
top-p = 0.95
min-p = 0.05
top-k = 40


[LFM 2.5 8B-A1B]
#https://huggingface.co/LiquidAI/LFM2.5-8B-A1B
#12.8 tok/s @ 1000 tok
model = /home/ava/LLMs/LFM2.5-8B-A1B-Q4_K_M.gguf
ctx-size = 10000
reasoning = on
reasoning-budget = 500
reasoning-budget-message = "I need to wrap this up and give an answer now"
temp = 1.0
top-p = 0.95
min-p = 0.05
top-k = 65

[Qwen 3.5 4B]
#https://huggingface.co/unsloth/Qwen3.5-4B-MTP-GGUF
#5.6 tok/s @ 1000 tok
model = /home/ava/LLMs/Qwen_3.5_4B/Qwen3.5-4B-Q4_K_M.gguf
spec-type = draft-mtp
spec-draft-n-min = 2
ctx-size = 10000
reasoning-budget = 300
reasoning-budget-message = "I need to wrap this up and answer right now"
temp = 1.0
top-p = 0.95
top-k = 20
repeat-penalty = 1.00

[Qwen 2.5 Coder 1.5B Code Completion]
#https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF
#12.5 tok/s @ 1000k
model = /home/ava/LLMs/Qwen2.5-Coder-1.5B-Instruct-Q4_K_M.gguf
ctx-size = 2000
reasoning = off
temp = 0.2
top-p = 0.9
min-p = 0.05
top-k = 40
repeat-penalty = 1.00
